/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a express boiler plate
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@example.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Id
 */
export interface Id {
  /**
   *
   * @type {string}
   * @memberof Id
   */
  id: string;
}
/**
 * Check if a given object implements the Id interface.
 */
export declare function instanceOfId(value: object): boolean;
export declare function IdFromJSON(json: any): Id;
export declare function IdFromJSONTyped(json: any, ignoreDiscriminator: boolean): Id;
export declare function IdToJSON(value?: Id | null): any;
