/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a express boiler plate
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@example.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersPost200Response
 */
export interface UsersPost200Response {
  /**
   *
   * @type {string}
   * @memberof UsersPost200Response
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UsersPost200Response
   */
  id: string;
}
/**
 * Check if a given object implements the UsersPost200Response interface.
 */
export declare function instanceOfUsersPost200Response(value: object): boolean;
export declare function UsersPost200ResponseFromJSON(json: any): UsersPost200Response;
export declare function UsersPost200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPost200Response;
export declare function UsersPost200ResponseToJSON(value?: UsersPost200Response | null): any;
