/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a express boiler plate
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@example.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersGet200Response
 */
export interface UsersGet200Response {
  /**
   *
   * @type {string}
   * @memberof UsersGet200Response
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UsersGet200Response
   */
  id: string;
}
/**
 * Check if a given object implements the UsersGet200Response interface.
 */
export declare function instanceOfUsersGet200Response(value: object): boolean;
export declare function UsersGet200ResponseFromJSON(json: any): UsersGet200Response;
export declare function UsersGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersGet200Response;
export declare function UsersGet200ResponseToJSON(value?: UsersGet200Response | null): any;
