/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a express boiler plate
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@example.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { User, UsersGet200Response, UsersPost200Response } from '../models/index';
export interface UserApiPostUserRequest {
  user: User;
}
/**
 * UserApi - interface
 *
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
  /**
   *
   * @summary get users
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UsersGet200Response>>;
  /**
   * get users
   */
  getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersGet200Response>;
  /**
   *
   * @summary post a user
   * @param {User} user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  postUserRaw(
    requestParameters: UserApiPostUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UsersPost200Response>>;
  /**
   * post a user
   */
  postUser(
    requestParameters: UserApiPostUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UsersPost200Response>;
}
/**
 *
 */
export declare class UserApi extends runtime.BaseAPI implements UserApiInterface {
  /**
   * get users
   */
  getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UsersGet200Response>>;
  /**
   * get users
   */
  getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersGet200Response>;
  /**
   * post a user
   */
  postUserRaw(
    requestParameters: UserApiPostUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UsersPost200Response>>;
  /**
   * post a user
   */
  postUser(
    requestParameters: UserApiPostUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UsersPost200Response>;
}
